name: GR00T Fine-tune
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["GR00T Setup"]
    types: [completed]

jobs:
  gr00t-finetune:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Step 0 - Install Brev CLI, login and enter Brev to create ssh config
        run: |
          sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/brevdev/brev-cli/main/bin/install-latest.sh)"
          echo "No" | brev login --token ${{ secrets.BREV_TOKEN }} --skip-browser
          brev shell ${{ vars.BREV_INSTANCE_NAME }}

      - name: Step 1 - Download Dataset
        run: ssh -F ~/.brev/ssh_config ${{ vars.BREV_INSTANCE_NAME }} "cd ~/Isaac-GR00T;
          export PATH=\$HOME/.local/bin:\$PATH;
          uv run hf download VoicAndrei/${{ vars.HF_REPO_NAME }} --repo-type dataset --local-dir ./hf_datasets/${{ vars.HF_REPO_NAME }};
          "
      
      
     # - name: Step 2 - Run finetune
    #  run: ssh -F ~/.brev/ssh_config ${{ vars.BREV_INSTANCE_NAME }} "cd ~/Isaac-GR00T;
     #     export NUM_GPUS=1;
      #    export PATH=\$HOME/.local/bin:\$PATH;
       #   CUDA_VISIBLE_DEVICES=0;
        #  uv run python gr00t/experiment/launch_finetune.py --base_model_path nvidia/GR00T-N1.6-3B --dataset_path ./hf_datasets/${{ vars.HF_REPO_NAME }} --modality_config_path ~/modality_files/${{ vars.MODALITY_FILE }} --embodiment_tag NEW_EMBODIMENT --num_gpus \$NUM_GPUS --output_dir tmp/${{ vars.HF_REPO_NAME }} --save_steps ${{ vars.SAVE_STEPS }} --save_total_limit 5 --max_steps ${{ vars.MAX_STEPS }} --warmup_ratio 0.05 --weight_decay 1e-5 --learning_rate 1e-4 --global_batch_size 32 --color_jitter_params brightness 0.3 contrast 0.4 saturation 0.5 hue 0.08 --dataloader_num_workers 4;
         # "

      - name: Step 2 - Launch finetune in tmux
        run: ssh -F ~/.brev/ssh_config ${{ vars.BREV_INSTANCE_NAME }} "
          tmux new-session -d -s counter;
          tmux send-keys -t counter './infinite_counter.sh' Enter;
          "